### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'insertAdjacentElement')

### ISSUE THREAD

**Issue by QuaCKeReD** [phibr0/obsidian-commander#18] opened 2022-08-30 10:01 UTC
### Describe the bug

Bug shows in dev console under new Obsidian v0.16.0 version
No obvious impact, at present

### Relevant errors (if available)

```Shell
app.js:1 TypeError: Cannot read properties of undefined (reading 'insertAdjacentElement')
    at fe.addActionContainer (plugin:cmdr:7:17508)
    at eval (plugin:cmdr:7:14260)
    at t.<anonymous> (app.js:1:1591813)
    at app.js:1:235192
    at Object.next (app.js:1:235297)
    at a (app.js:1:234036)
```

### Steps to reproduce

Install plugin on Obsidian 16.0

### Operating system

macOS

**Comment by phibr0** [comment] 2022-08-30 10:24
Will try my best to fix compatibility soonish. That error is caused by the right ribbon not being there anymore

**Comment by phibr0** [comment] 2022-08-31 08:37
Fixed in the new release

**Closed by phibr0** 2022-08-31 08:37 UTC

**Comment by QuaCKeReD** [comment] 2022-08-31 09:20
Updated and confirmed! Thanks!
